import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // 1. Main Page
    'main-page',

    // 2. Live Game Data
    {
      type: 'category',
      label: 'Live Game Data',
      link: {type: 'doc', id: 'game-data/index'},
      items: [{type: 'autogenerated', dirName: 'game-data'}],
    },

    // 3. From others Wiki (Wiki Fandom + Database)
    {
      type: 'category',
      label: 'From others Wiki',
      items: [
        {
          type: 'category',
          label: 'Wiki (Fandom)',
          items: [{type: 'autogenerated', dirName: 'wiki'}],
        },
        {
          type: 'category',
          label: 'Database',
          link: {type: 'doc', id: 'database/index'},
          items: [{type: 'autogenerated', dirName: 'database'}],
        },
      ],
    },

    // 4. Sources & Credits
    'sources',

    // Useful Links (conservé en fin de menu)
    'liens-utiles',
  ],
};

export default sidebars;
