import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // 1. Main Page
    'main-page',

    // 2. Live Game Data
    {
      type: 'category',
      label: 'Live Game Data',
      link: {type: 'doc', id: 'game-data/index'},
      items: [
        {type: 'autogenerated', dirName: 'game-data/items'},
        {type: 'autogenerated', dirName: 'game-data/mobs'},
        {type: 'autogenerated', dirName: 'game-data/pets'},
        {type: 'autogenerated', dirName: 'game-data/recipes'},
      ],
    },

    // 3. From others Wiki (Wiki Fandom + Database)
    {
      type: 'category',
      label: 'From others Wiki',
      items: [
        {
          type: 'category',
          label: 'Wiki (Fandom)',
          items: [
            {type: 'autogenerated', dirName: 'wiki/autres'},
            {type: 'autogenerated', dirName: 'wiki/collecte'},
            {type: 'autogenerated', dirName: 'wiki/competences'},
            {type: 'autogenerated', dirName: 'wiki/equipement'},
            {type: 'autogenerated', dirName: 'wiki/monstres-boss'},
            {type: 'autogenerated', dirName: 'wiki/nourriture'},
            {type: 'autogenerated', dirName: 'wiki/pets'},
            {type: 'autogenerated', dirName: 'wiki/pnj'},
          ],
        },
        {
          type: 'category',
          label: 'Database',
          link: {type: 'doc', id: 'database/index'},
          items: [
            {type: 'autogenerated', dirName: 'database/guides'},
            {type: 'autogenerated', dirName: 'database/items'},
            {type: 'autogenerated', dirName: 'database/mobs'},
            {type: 'autogenerated', dirName: 'database/pets'},
            {type: 'autogenerated', dirName: 'database/recipes'},
            {type: 'autogenerated', dirName: 'database/vendors'},
          ],
        },
      ],
    },

    // 4. Sources & Credits
    'sources',

    // Useful Links (conservé en fin de menu)
    'liens-utiles',
  ],
};

export default sidebars;
