import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // 1. Main Page
    'main-page',

    // 2. Live Game Data
    {type: 'autogenerated', dirName: 'game-data'},

    // 3. From others Wiki (Wiki Fandom + Database)
    {
      type: 'category',
      label: 'From others Wiki',
      items: [
        {type: 'autogenerated', dirName: 'wiki'},
        {type: 'autogenerated', dirName: 'database'},
      ],
    },

    // 4. Sources & Credits
    'sources',

    // Useful Links (conservé en fin de menu)
    'liens-utiles',
  ],
};

export default sidebars;
